export const AI_SDK_SCHEMA_VERSIONS = {
  pipelineDefinition: 1,
  pipelinePublicationRequest: 1,
  pipelinePublicationResponse: 1,
  executionSubmissionRequest: 1,
  executionSubmissionResponse: 1,
  executionObservation: 1,
  executionResult: 1,
  executionCancellationRequest: 1,
  executionCancellationResponse: 1,
  executionControlRequest: 1,
  executionControlResponse: 1,
  executionInputSubmissionRequest: 1,
  executionReplayRequest: 1,
  executionReplayResponse: 1,
  executionWatchRequest: 1,
  executionWatchEvent: 1,
  executionWatchResyncRequired: 1,
} as const;
