using Multiplexed.Abstractions.AI.ControlPlane.RuntimeInstances.HostManager;

namespace Multiplexed.AI.Runtime.ControlPlane.RuntimeInstances.HostManager.Pool.Kubernetes.Failure
{
    /// <summary>
    /// Requests fresh Kubernetes Runtime Pool Pod capacity under one active Pod recovery claim.
    /// </summary>
    public sealed record AiKubernetesRuntimePoolPodReplacementRequest
    {
        /// <summary>
        /// Gets the exact failed-Pod inventory and active recovery lease acquired in the
        /// preceding recovery-claim boundary.
        /// </summary>
        public required AiKubernetesRuntimePoolPodClaimedAssignedWork
            ClaimedAssignedWork { get; init; }

        /// <summary>
        /// Gets the provider-owned host request whose execution, tenant, isolation, and
        /// capacity settings are copied into the fresh replacement request.
        /// </summary>
        /// <remarks>
        /// Replacement identity fields are generated by the coordinator. The template's
        /// RequestId, HostId, RuntimeInstanceId, endpoint, and metadata are not reused.
        /// </remarks>
        public required AiRuntimeHostStartRequest HostStartTemplate { get; init; }
    }
}
