class AiSdkSchemaVersions:
    PIPELINE_DEFINITION = 1
    PIPELINE_PUBLICATION_REQUEST = 1
    PIPELINE_PUBLICATION_RESPONSE = 1
    EXECUTION_SUBMISSION_REQUEST = 1
    EXECUTION_SUBMISSION_RESPONSE = 1
    EXECUTION_OBSERVATION = 1
    EXECUTION_RESULT = 1
    EXECUTION_CANCELLATION_REQUEST = 1
    EXECUTION_CANCELLATION_RESPONSE = 1
