using System.Text.Json.Serialization;

namespace Multiplexed.Abstractions.AI.Invocation
{
    /// <summary>
    /// Describes how an implementation is invoked. References are publication/connection
    /// identifiers, not source code, credentials, worker identities, or arbitrary URLs.
    /// Resolution of a reference does not itself authorize or load it.
    /// </summary>
    public sealed record AiInvocationDefinition
    {
        /// <summary>
        /// Must be explicit when this descriptor is present. A missing descriptor,
        /// not an empty descriptor, is the backward-compatible native form.
        /// </summary>
        [JsonPropertyName("kind")]
        public AiInvocationKind? Kind { get; init; }

        /// <summary>Reference generated by publication for a custom implementation.</summary>
        [JsonPropertyName("implementationRef")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? ImplementationRef { get; init; }

        /// <summary>Server-resolved connection identifier for an MCP step.</summary>
        [JsonPropertyName("connectionRef")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? ConnectionRef { get; init; }

        /// <summary>Tool name within the authorized MCP connection.</summary>
        [JsonPropertyName("tool")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? Tool { get; init; }
    }
}
